spring.application.name=discografia
spring.mongodb.uri=mongodb+srv://miguel32x_db_user:QaBUlt2y8jey3ee1@eva-u2-spring.tu4xpfq.mongodb.net/?appName=eva-u2-spring
spring.mongodb.database=Discografia-db
